version: '3.7'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 80:8000
    environment:
        - DEBUG=1
        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    restart: unless-stopped
    networks:
      - englishjust-backend-tier

networks:
  englishjust-backend-tier:
    driver: bridge